# Changes here will be overwritten by Copier
_commit: 4.2.0
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: iain.hall@diamond.ac.uk
author_name: Iain Hall
component_lifecycle: experimental
component_owner: group:default/daq
component_type: library
description: Plans to use at spectroscopy beamlines at DLS
distribution_name: spectroscopy-bluesky
docker: true
docker_debug: false
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: spectroscopy_bluesky
pypi: true
repo_name: spectroscopy-bluesky
strict_typing: true
type_checker: pyright
