apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: hello
spec:
  entrypoint: hello
  volumeClaimTemplates:
    - metadata:
        name: outputs
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
    - metadata:
        name: tmp
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path

  templates:
  - name: install-requirements
    script:
      image: docker.io/library/python:bookworm
      command: ["sh", "-c"]
      args:
        - |
          cat <<EOF > /tmp/requirements.txt
          {{- .Files.Get "notebooks/requirements.txt" | nindent 12 }}
          EOF
      volumeMounts:
        - name: tmp
          mountPath: /tmp

  - name: nbconvert-install
    script:
      image: docker.io/library/python:bookworm
      command: [bash]
      source: |
        mkdir -p /tmp/.config/matplotlib
        mkdir -p /tmp/.ipython
        python -m venv /tmp/venv
        /tmp/venv/bin/pip install -r /tmp/requirements.txt --no-cache-dir
        /tmp/venv/bin/python -m ipykernel install --prefix=/tmp/venv --name=venv
              volumeMounts:
        - name: outputs
          mountPath: /outputs
        - name: tmp
          mountPath: /tmp

  - name: convert
    script:
      image: docker.io/library/python:bookworm
      command:
        - /tmp/venv/bin/python
        - -m
        - nbconvert
        - --execute
        - --allow-errors
        - --to
        - html
        - --output
        - notebook
        - --output-dir
        - /outputs
      source: |
        {{- .Files.Get "notebooks/hello.ipynb" | fromJson | toPrettyJson | nindent 8 }}
      volumeMounts:
        - name: outputs
          mountPath: /outputs
        - name: tmp
          mountPath: /tmp
    outputs:
      artifacts:
      - name: notebook
        path: /outputs/notebook.html
        archive:
          none: {}

  - name: notebook
    dag:
      tasks:
      - name: requirements
        template: install-requirements
      - name: install
        template: nbconvert-install
        dependencies: [requirements]
      - name: convert
        template: convert
        dependencies: [install]
